apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 3-tier-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "postgres"
  replicas: {{ .Values.replicaCount.postgres }}
  selector:
    matchLabels:
      app: 3-tier-db
  template:
    metadata:
      labels:
        app: 3-tier-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.images.postgres }}
        ports: 
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.size }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: 3-tier-db
  type: ClusterIP