apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  CLERK_SECRET_KEY: {{ .Values.clerk.secretKey | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_USER: {{ .Values.database.user | quote }}