apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  namespace: 3-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: backend1
          image: madhu092/backend1:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND1_PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_CLIENT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: CLERK_PUBLISHABLE_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: CLERK_SECRET_KEY
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_URL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER

---
apiVersion: v1
kind: Service
metadata:
  name: backend1
  namespace: 3-tier
spec:
  selector:
    app: backend1
  ports:
    - port: 3000
      targetPort: 3000