apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: 3-tier
data:
  BACKEND1_PORT: "3000"
  BACKEND2_PORT: "3001"
  DB_PORT: "5432"
  DB_HOST: "postgres"
  DB_NAME: "madhu_db"
  DB_CLIENT: "pg"
  NODE_ENV: "local"
  CLERK_PUBLISHABLE_KEY: "pk_test_ZmlybS1lYXJ3aWctODIuY2xlcmsuYWNjb3VudHMuZGV2JA"
  FRONTEND_URL: "http://localhost:80"
  VITE_BACKEND1_BASE_URL: "http://madhu.blog.com/backend1"
  VITE_BACKEND2_BASE_URL: "http://madhu.blog.com/backend2"
