apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: 3-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: madhu092/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_CLERK_PUBLISHABLE_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CLERK_PUBLISHABLE_KEY
            - name: VITE_BACKEND1_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VITE_BACKEND1_BASE_URL
            - name: VITE_BACKEND2_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VITE_BACKEND2_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: 3-tier
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
